# -*- coding: utf-8 -*-
"""Robot_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PX_ovTH1qQCPdjUQVWimnW1femjCVQHD
"""

# Load data
import pandas as pd
df = pd.read_csv('InsideJLabWifiMeasurement.csv')     # Read data file
x = df.get('Time').to_numpy()[:-1]
first_trial=df.get('1st Trial').to_numpy()[:-1]
second_trial=df.get('2nd Trial').to_numpy()[:-1]
third_trial=df.get('3rd Trial').to_numpy()[:-1]
fourth_trial=df.get('4th Trial').to_numpy()[:-1]



# NOTE: The text header is automatically removed.

# Optional print statement to see if loaded data are present
print("x = ", x[0])
print("x = ", x[1])
print("First Trial = ", first_trial[1])
print("Second Trial = ", second_trial[1])
print("Third Trial = ", third_trial[1])
print("Fourth Trial = ", fourth_trial[1])

# import library modules needed for plotting and data analysis
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import gridspec
from google.colab import files


# import library module for curve fitting
from scipy.optimize import curve_fit

gs = gridspec.GridSpec(2, 2)

title = "R-Pi Wi-Fi Monitoring (Inside JLab)"
xlabel = "Time (s)"
ylabel = "Wi-Fi Transfer Rate (Mbits/sec)"

fig1=plt.figure(1)

#fig1, (ax1,ax2,ax3,ax4) = plt.subplots(nrows=4, sharex=True, subplot_kw=dict(frameon=False)) # frameon=False removes frames

plt.subplots_adjust(hspace=.0)
fig1.suptitle(title)                           # Add the plot title



ax0 = plt.subplot(gs[0])
ax1 = plt.subplot(gs[1], sharex=ax0)
ax2 = plt.subplot(gs[2], sharex=ax0)
ax3 = plt.subplot(gs[3], sharex=ax0)


line0, = ax0.plot(x, first_trial, color='r', linestyle='--')
line1, = ax1.plot(x, second_trial, color='b', linestyle='-.')
line2, = ax2.plot(x, third_trial, color='g', linestyle=':')
line3, = ax3.plot(x, fourth_trial, color='k')

fig1.supylabel(ylabel, fontsize=10)                     # Add the y-axis label, "fontsize" is optional
fig1.supxlabel(xlabel, fontsize=10)                            # Add the x-axis label, "fontsize" is optional

ax0.legend((line0, line1, line2, line3), ('Trial 1', 'Trial 2','Trial 3', 'Trial 4'), loc='lower left')

ax0.plot(x, first_trial, color='r', linestyle='--')
ax1.plot(x, second_trial, color='b', linestyle='-.')
ax2.plot(x, third_trial, color='g', linestyle=':')
ax3.plot(x, fourth_trial, color='k')

# remove vertical gap between subplots
plt.subplots_adjust(hspace=.0)
plt.show()

# Plot the data on a new figure
fig1.show()

fig_filename = 'Wi-FiMonitoring(InsideJLab)_graph.pdf'
fig1.savefig(fig_filename)
files.download(fig_filename)

